name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: psh ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
          - goarch: amd64
            goos: windows
            goexe: .exe
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: build
        run: make psh
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: package
        run: |
          mv bin/psh bin/psh${{ matrix.goexe }} && mv template/psh.yaml bin/psh.yaml
          tar -zcvf psh_${{ matrix.goos }}_${{ matrix.goarch }}.tgz -C bin .
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: psh_${{ matrix.goos }}_${{ matrix.goarch }}.tgz
          asset_name: psh_${{ matrix.goos }}_${{ matrix.goarch }}.tgz
          asset_content_type: application/gzip
